name: publish docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: "./gh-pages"
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Fix folder structure
        run: mv gh-pages/docs docs
        continue-on-error: true

      - name: Clean up gh-pages
        run: rm -rf gh-pages

      - name: Setup node.js @ lts
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate API reference
        run: pnpm build:docs

      - name: Publish to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          target-folder: docs
